# ドキュメントのタイトル ( ブラウザのタブなどに表示される )
site_name: TechnoTUT Docs

# テーマの指定 ( mkdocs-material を指定する )
theme:
  name: material
  language: ja 

# Navigation
nav:
    - Welcome: 'index.md'
    - 'User Guide':
        - 'このドキュメントの書き方': 'writing-your-docs.md'
    - 'ホームページ':
        - '構成': 'hp/hp-config.md'
        - '書き方': 'hp/writing-your-hp.md'
    - VJ:
        - '配線': 'vj/wire.md'
        - 'ネットワーク': 
          - 'NDI': 'vj/ndi.md'
          - 'ネットワーク構成': 'vj/network.md'
# その他の設定
extra:
  search:
    language: "ja"  # 日本語での検索に対応
  font:
    text: "Noto Sans JP"  # フォントの変更
    code: "Consolas"  # 埋め込みコードのフォントの変更

copyright: Copyright &copy; 2014 - 2022 TechnoTUT  # フッターに表示するコピーライト

# CSS の設定
extra_css:
  - "css/custom.css"  # このあと作成する CSS ファイル
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"  # 外部 CSS の読み込みを行いフォントを帰る
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

# 拡張機能
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde